fix: Fix parsing error for grub-efi recipe when building with Mender disabled
When the meta-mender stack is included but the distro is building without
Mender (such as for testing), an error is raised.

Error was:

  ERROR: ExpansionError during parsing grub-efi-mender-precompiled_2.04.bb
  Traceback (most recent call last):
    File "<expansion>", line 1, in <module>
  bb.data_smart.ExpansionError: Failure expanding expression ${@'uboot_version_logic.inc' if d.getVar('MENDER_EFI_LOADER').startswith('u-boot') else ''} which triggered exception AttributeError: 'NoneType' object has no attribute 'startswith'

Changelog: Fixes parsing error with Mender disabled

Ticket: None

Signed-off-by: Garrett Brown <garrett.brown@aclima.io>
(cherry picked from commit 371b71b4812740414a2378720cd60c9e19a87879)