mender-client: fix install of systemd-machine-id.service
Fix for the the following:

ERROR: mender-client-2.3.0-r0 do_package: QA Issue: mender-client: Files/directories were installed but not shipped in any package:
  /lib/systemd/system/mender-client-systemd-machine-id.service

This service is installed with a name based on the MENDER_CLIENT
variable, but this variable was not used in FILES. Previously, the
file names matched, but it now needs to be updated as the value of
MENDER_CLIENT has been changed.

Changelog: Title

Signed-off-by: Kurt Kiefer <kekiefer@gmail.com>
(cherry picked from commit e8a27c3bb5fe279d052ddfe80bbd95af7bef5d6d)