mender-helpers: Don't rely on creating a hardlink ...
... in function mender_merge_bootfs_and_image_boot_files

While copying the image boot files, creating a hardlink only works if the
paths are below the same mountpoint.

Otherwise running the task do_image_sdimg results in the following error:

WARNING: /<TMPDIR>/work/<MACHINE>/<IMAGE>/1.0-r0/temp/run.do_image_sdimg.22140:1 exit 1 from 'cp -l "$file" "$destfile"'
ERROR: Function failed: do_image_sdimg (log file is located at /<TMPDIR>/work/<MACHINE>/<IMAGE>/1.0-r0/temp

A case where this happens is when DEPLOY_DIR (or DEPLOY_DIR_IMAGE) points
to a path which is on a different mount point than the WORKDIR.

Changelog: none

Signed-off-by: Joerg Hofrichter <joerg.hofrichter@ni.com>
(cherry picked from commit c2d5f2d7a4cab534e93030e5a1416e225fb60e60)

Backported-by: Lluis Campos <lluis.campos@northern.tech>

Backported to thud fixing mender-part-images instead of mender-helpers