Fix boot failure on ARM UEFI devices because of missing `regexp` module.
Changelog: Fix boot failure on ARM UEFI devices because of missing
`regexp` module. A typical error log looks like this:
```
Welcome to GRUB!

error: no such device: ((hd0,msdos1)/efi/boot)/EFI/BOOT/grub.cfg.
lock: OK
lock: OK
error: can't find command `regexp'.

error: disk `,msdos2' not found.

Dropping to grub prompt for unknown reason. Should never get here.
```

It happened because the binary `grub-efi-bootarm.efi` file was not
updated when the regexp module was added as a requirement. Fixed by
grabbing it from the vexpress-qemu UEFI build.

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>