u-boot-mender: Ignore case when checking variables in mender_Kconfig_fragment
Fixes:

ERROR: u-boot-fslc-v2020.04+gitAUTOINC+88c58453be-r0 do_configure: U-Boot configuration  pico-dwarf-imx7d_defconfig pico-nymph-imx7d_defconfig pico-pi-imx7d_defconfig has setting:
CONFIG_ENV_OFFSET=0xC0000
but Mender expects:
CONFIG_ENV_OFFSET=0xc0000
Please fix U-Boot's configuration file.
...

So, let's ignore case during comparison by adding '-i' option to fgrep

Changelog: Title

Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>
(cherry picked from commit 5b991a9f089e409323f31c0f4c0691243d52f6e0)

zeus: moved the fix to u-boot-mender-common.inc instead

Signed-off-by: Lluis Campos <lluis.campos@northern.tech>