test: improve test_uboot_automation.py
Fix spurious errors when reading binary data from the file:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 1435: invalid start byte

Changelog: None
Ticket: None

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>
(cherry picked from commit a1a3954b4dd719b8a811c7af1ba9feb6b0aa91bf)