Fix ERROR: Nothing RPROVIDES 'linux-firmware-raspbian-bcm43430'
Issue during build process as follows:

ERROR: Nothing RPROVIDES 'linux-firmware-raspbian-bcm43430'

NOTE: Runtime target 'linux-firmware-raspbian-bcm43430' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['linux-firmware-raspbian-bcm43430']
ERROR: Required build target 'core-image-base' has no buildable providers.

Changelog: Fixed issue with build due to unknown image linux-firmware-raspbian-bcm43430
Signed-off-by: Karim Gillani <karim.gillani@gov.bc.ca>
(cherry picked from commit ad9b2afd8896f3e065c4adaa257328e4a716bd77)