Adjust the Raspberry Pi patch to match default alignment.
The patch was always out of sync, but this is needed now because it is
not auto-fixed anymore, it has to match MENDER_PARTITION_ALIGNMENT.

Changelog: Fix error message about `CONFIG_ENV_OFFSET` being wrong,
such as:
```
ERROR: u-boot-fw-utils-mender-auto-provided-1.0-r0 do_configure: U-Boot configuration rpi_4_config has setting:
CONFIG_ENV_OFFSET=0x400000
CONFIG_ENV_OFFSET_REDUND=0x800000
but Mender expects:
CONFIG_ENV_OFFSET=0x800000
Please fix U-Boot’s configuration file.
```

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
(cherry picked from commit cea90925e233de413860e9543efde7a7d3c0ef12)