mender-artifact(3.0.0b1):Add "xz" build dependency
Changelog: Add missing build dependency on "xz" in Mender Artifact recipe for 3.0.0b1 version

This dependency should be added to resolve the below error:
| # github.com/mendersoftware/mender-artifact/vendor/github.com/mendersoftware/go-liblzma
| ../../../../../../../build/src/github.com/mendersoftware/mender-artifact/vendor/github.com/mendersoftware/go-liblzma/reader.go:9:18: fatal error: lzma.h: No such file or directory
| compilation terminated.

Signed-off-by: Ajith P Venugopal <ajithpv@outlook.com>
(cherry picked from commit e9585a446f8690729f66e0fce675a033b457ca05)