u-boot-mender.inc: use upper case hex values for HEX_MENDER_UBOOT_ENV_STORAGE_DEVICE_OFFSET_1 and 2
U-boot .config files default to upper case hex for CONFIG values, so if the HEX_MENDER_UBOOT_ENV_STORAGE_DEVICE_OFFSET_1 or 2 setting contains an alpha character the subsequent string based test fails:

ERROR: u-boot-stm32mp-2020.01-r0 do_configure: U-Boot configuration  stm32mp15_basic_defconfig has setting:
CONFIG_ENV_OFFSET_REDUND=0x2C0000
but Mender expects:
CONFIG_ENV_OFFSET_REDUND=0x2c0000
Please fix U-Boot's configuration file.

Changing the setting to lower case in the u-boot source isn't a valid workaround since u-boot up-shifts it when creating the defconfig.

Signed-off-by: Steve Sakoman <steve@sakoman.com>